title: Your awesome title
author: Jov Emmanuel R. Ermitaño
email: jovermitano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Hello, Github! Still confused with the terminologies here. 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
